<?php
/**
 * InlineResponse2002DataItemsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Teletype Public API
 *
 * ## Общая информация Вы можете использовать данную документацию для ознакомления с методами API. Описание произведено в формате [**Swagger 3.0**](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md). Для генерации базового кода для работы с API на удобном для вас языке программирования воспользуйтесь утилитой [**Swagger Codegen**](https://swagger.io/swagger-codegen/) или online сервисом [**Swagger Editor**](https://editor.swagger.io/).  По всем вопросам работы с API обращайтесь к нам по email: <a href=\"mailto:p@teletype.app\">p@teletype.app</a></li>
 *
 * OpenAPI spec version: 1.0.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.16
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InlineResponse2002DataItemsTest Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse2002DataItems
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse2002DataItemsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse2002DataItems"
     */
    public function testInlineResponse2002DataItems()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "is_online"
     */
    public function testPropertyIsOnline()
    {
    }

    /**
     * Test attribute "last_online_at"
     */
    public function testPropertyLastOnlineAt()
    {
    }

    /**
     * Test attribute "phone_is_locked"
     */
    public function testPropertyPhoneIsLocked()
    {
    }

    /**
     * Test attribute "email_is_locked"
     */
    public function testPropertyEmailIsLocked()
    {
    }

    /**
     * Test attribute "banned"
     */
    public function testPropertyBanned()
    {
    }

    /**
     * Test attribute "average_rate"
     */
    public function testPropertyAverageRate()
    {
    }

    /**
     * Test attribute "first_message_at"
     */
    public function testPropertyFirstMessageAt()
    {
    }

    /**
     * Test attribute "last_message_at"
     */
    public function testPropertyLastMessageAt()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "avatar"
     */
    public function testPropertyAvatar()
    {
    }

    /**
     * Test attribute "avatar_original"
     */
    public function testPropertyAvatarOriginal()
    {
    }

    /**
     * Test attribute "color"
     */
    public function testPropertyColor()
    {
    }

    /**
     * Test attribute "animal"
     */
    public function testPropertyAnimal()
    {
    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }
}
